import type { SchemaGraph, SchemaColumn } from '../sql/types';

function columnConstraints(col: SchemaColumn): string {
  const parts: string[] = [];
  if (col.isPrimaryKey) parts.push('`PK`');
  if (col.isForeignKey && col.references) parts.push(`\`FK → ${col.references.table}.${col.references.column}\``);
  if (col.isUnique && !col.isPrimaryKey) parts.push('`UNIQUE`');
  if (col.isIndexed) parts.push('`INDEX`');
  if (col.isNotNull && !col.isPrimaryKey) parts.push('`NOT NULL`');
  return parts.join(' ');
}

export function generateSchemaDocs(graph: SchemaGraph): string {
  const lines: string[] = [
    '# Database Schema Documentation',
    '',
    `> Generated by [SQL Visualizer](https://sql-visualizer-theta.vercel.app) on ${new Date().toLocaleDateString()}`,
    '',
    '## Tables',
    '',
  ];

  // Table of contents
  for (const node of graph.nodes) {
    lines.push(`- [${node.tableName}](#${node.tableName.toLowerCase().replace(/[^a-z0-9]/g, '-')})`);
  }
  lines.push('');

  // Each table
  for (const node of graph.nodes) {
    lines.push(`## ${node.tableName}`);
    lines.push('');
    if (node.compositePK) {
      lines.push(`**Composite Primary Key:** \`(${node.compositePK.join(', ')})\``);
      lines.push('');
    }
    lines.push('| Column | Type | Constraints |');
    lines.push('|--------|------|-------------|');
    for (const col of node.columns) {
      const constraints = columnConstraints(col);
      lines.push(`| \`${col.name}\` | \`${col.dataType || '—'}\` | ${constraints || '—'} |`);
    }
    lines.push('');
  }

  // Relationships section
  if (graph.edges.length > 0) {
    lines.push('## Relationships');
    lines.push('');
    lines.push('| From Table | Column | To Table | Column |');
    lines.push('|------------|--------|----------|--------|');
    for (const edge of graph.edges) {
      const fromNode = graph.nodes.find((n) => n.id === edge.source);
      const toNode = graph.nodes.find((n) => n.id === edge.target);
      if (fromNode && toNode) {
        lines.push(`| \`${fromNode.tableName}\` | \`${edge.sourceColumn}\` | \`${toNode.tableName}\` | \`${edge.targetColumn}\` |`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function downloadSchemaDocs(graph: SchemaGraph): void {
  const md = generateSchemaDocs(graph);
  const blob = new Blob([md], { type: 'text/markdown' });
  const a = document.createElement('a');
  a.download = `schema-docs-${new Date().toISOString().slice(0, 10)}.md`;
  a.href = URL.createObjectURL(blob);
  a.click();
  URL.revokeObjectURL(a.href);
}
